# -*- coding: utf-8 -*-
"""Pool d'angles ETENDU (v2, mots-cles suffixe sans collision)."""

ANG_EXTRA = {
"loisir": [
 (("entre amis","potes","copains","bande"),
  "Une sortie {a} {loc} entre amis, c'est l'assurance d'un bon moment : de l'action, des fous rires et zero organisation.",
  "Le {a}, la valeur sure entre potes",
  "Le {a} se joue a plusieurs et l'ambiance monte avec le nombre. Sur 7 500 m2 a 25 minutes de Lille, on enchaine le {a} avec une autre des 22 activites, une pause au bar entre deux, et une tournee offerte si vous reservez plusieurs activites. Reservez en ligne avec le **code TS10** pour -10 %."),
 (("ados","adolescents"),
  "Vous cherchez une activite {loc} pour un groupe d'ados qui en demande toujours plus ? Le {a} a tout pour leur plaire.",
  "Le {a} pour un groupe d'ados",
  "Encadre par un animateur dedie, le {a} canalise l'energie des ados dans un cadre securise. On adapte le rythme et on peut enchainer plusieurs activites. Ideal pour un anniversaire ado ou une sortie de groupe, avec un espace privatisable et le gateau autorise."),
 (("sensations","adrenaline","frisson"),
  "Envie de sensations fortes {loc} ? Le {a} fait grimper l'adrenaline tout en restant accessible a tous.",
  "Des sensations, en toute securite",
  "Le {a} mele montee d'adrenaline et plaisir de jeu, avec un briefing de securite avant de lancer et un animateur dedie. On adapte l'intensite au groupe, des plus prudents aux plus temeraires. Et pour prolonger les frissons, le parc compte plus de 22 activites au meme endroit."),
 (("vaut le coup","pourquoi essayer"),
  "Le {a} {loc}, ca vaut le coup ? Si vous hesitez encore, voici ce qui fait mouche a chaque fois.",
  "Pourquoi le {a} fait l'unanimite",
  "Accessible sans experience, encadre, et adaptable a tous les groupes : le {a} met tout le monde d'accord. Le parc affiche 4,7/5 sur Google depuis 2016 et plus de 100 000 visiteurs par an. Vous arrivez, un animateur s'occupe de tout, et il ne reste qu'a profiter. Premier essai conseille en reservant en ligne avec le **code TS10**."),
 (("derniere minute","dernière minute"),
  "Une envie de {a} {loc} de derniere minute ? On vous explique comment reserver vite et bien.",
  "Reserver a la derniere minute",
  "Selon les disponibilites, on accueille volontiers les groupes qui s'y prennent au dernier moment. A moins de 72 h, la reservation se fait **par telephone au 03 74 83 02 02** pour bien dimensionner l'equipe. Au-dela, reservez en ligne avec le **code TS10** pour -10 %, paiement a la reservation."),
 (("code promo","promo","reduction","réduction"),
  "Comment payer votre {a} {loc} moins cher ? Une astuce simple permet d'economiser a chaque reservation.",
  "-10 % avec le code TS10",
  "En reservant en ligne et en reglant a la reservation, le **code TS10** vous fait economiser **10 %** sur le tarif du jour, meme le samedi (offre non cumulable). Pensez aussi au tarif de semaine, plus doux que le samedi, et a la tournee offerte entre deux activites enchainees."),
 (("ouverte a tous","ouverte à tous","sortie ouverte"),
  "Le {a} {loc} est-il ouvert a tous ? On fait le point pour que personne ne reste sur le banc de touche.",
  "Une activite ouverte a tous",
  "Le {a} s'adapte a un large public ; l'animateur module les regles et le rythme selon les participants. Le parc dispose d'un parking gratuit et surveille a 25 minutes de Lille. Pour un besoin particulier, signalez-le a la reservation : l'equipe vous conseille la meilleure formule au 03 74 83 02 02."),
 (("nocturne",),
  "Et si vous testiez le {a} {loc} en version nocturne ? L'activite prend une autre dimension une fois la nuit tombee.",
  "Le {a} version nocturne",
  "Le parc reste ouvert en soiree, de quoi vivre le {a} dans une ambiance differente, puis prolonger avec un pack soiree privatise (salle, restauration, boissons, karaoke). Ideal pour un anniversaire ou un EVG/EVJF qui demarre l'apres-midi et se termine tard. Reservez en ligne avec le **code TS10**."),
 (("quelle activite","quelle activité"),
  "Difficile de choisir parmi toutes les activites {loc} ? On vous aide a savoir si le {a} est fait pour votre groupe.",
  "Le {a} est-il l'activite qu'il vous faut ?",
  "Le {a} convient aux groupes qui aiment l'action et le jeu collectif, debutants comme inities. Si vous hesitez, sachez qu'on peut en combiner plusieurs : le parc compte plus de 22 activites au meme endroit. Decrivez votre groupe a l'equipe, elle vous oriente au 03 74 83 02 02."),
 (("plusieurs activites","plusieurs activités","enchainer"),
  "Pourquoi se limiter a une seule activite {loc} ? En enchainer plusieurs transforme une sortie en vraie journee.",
  "Enchainer les activites sur une journee",
  "Sur 7 500 m2, on passe facilement du {a} a une autre des 22 activites, avec une **tournee de boissons offerte** entre deux et une pause au bar. On cale le planning avec vous (arrivee, activites, repas) pour une journee fluide. Une restauration sur place et un espace privatisable completent le tout."),
],
"party": [
 (("souvenir","immortaliser"),
  "Comment garder un souvenir memorable {un} {loc} ? Quelques idees pour immortaliser la journee.",
  "Des souvenirs plein la tete",
  "Photos et videos sont autorisees sur les activites : de quoi capturer les meilleurs moments. Entre les deguisements, les tee-shirts personnalises et les temps forts, les occasions de bons cliches ne manquent pas. Et la soiree privatisee prolonge la fete tard dans la nuit."),
 (("petit comite","petit comité","a quelques","à quelques"),
  "Faut-il etre nombreux pour {un} {loc} ? Bonne nouvelle : meme a quelques-uns, la fete est reussie.",
  "Reussir la fete en petit comite",
  "L'evenement fonctionne tres bien en petit groupe : on adapte les activites et l'espace au nombre. Plusieurs activites se pretent aux petits effectifs, et une salle karaoke intimiste peut accueillir un petit groupe. Un appel suffit pour caler la formule au 03 74 83 02 02."),
 (("theme","thème","ambiance"),
  "Envie de donner un theme a {un} {loc} ? On vous aide a creer l'ambiance qui fera la difference.",
  "Une ambiance a votre image",
  "Salle privatisee a decorer selon votre theme (installation possible selon disponibilite), deguisements et tee-shirts personnalises, karaoke et playlist : on pose le decor. Cote jeux, on choisit ceux qui collent a l'ambiance recherchee, du fun a l'adrenaline. L'equipe vous conseille sur ce qui est possible."),
 (("gateau","gâteau"),
  "Peut-on apporter son gateau pour {un} {loc} ? Spoiler : oui, et on vous dit ce qui est prevu.",
  "Votre gateau est le bienvenu",
  "Vous pouvez apporter votre propre gateau. Pour un anniversaire enfant, la formule prevoit meme un gateau et des surprises offertes. La restauration (cocktail dinatoire, burgers, pizzas) et les tickets boissons completent la fete. Tout est pense pour que vous n'ayez qu'a souffler les bougies."),
 (("alcool",),
  "Quelles boissons pour {un} {loc}, et peut-on prevoir une fete sans alcool ? On fait le tour des options.",
  "Boissons : avec ou sans alcool",
  "Selon la formule, les boissons fonctionnent par tickets ou en libre-service : softs, bieres et alcools forts cote pack soiree (champagne et cocktails exclus du forfait). Une fete 100 % softs est tout a fait possible. Une **tournee est offerte** entre deux jeux, et on adapte les quantites a votre groupe."),
 (("tournee","tournée"),
  "Saviez-vous qu'{un} {loc} peut inclure une tournee offerte ? Petit plus qui fait toujours plaisir.",
  "Une tournee offerte entre deux jeux",
  "Quand vous enchainez plusieurs activites, une **tournee de boissons est offerte** entre deux (softs, bieres, alcools forts ; champagne et cocktails exclus). De quoi souffler et trinquer avant de repartir, dans un cadre convivial a 25 minutes de Lille, encadre par un animateur dedie."),
 (("karaoke","karaoké","chansons"),
  "Et si {un} {loc} se terminait en chansons ? Le karaoke met l'ambiance et reunit tout le monde.",
  "Le karaoke pour finir en beaute",
  "Avec plus de 25 000 titres, le karaoke est l'option parfaite pour cloturer la journee dans la bonne humeur, en salle privatisee. On peut le combiner a un pack soiree (restauration, boissons) pour prolonger tard. Ideal apres une apres-midi d'activites, pour un final qui rassemble."),
 (("acces","accès","parking"),
  "Vos invites viennent de toute la region pour {un} {loc} ? L'acces facile simplifie l'organisation.",
  "Un acces simple, un parking gratuit",
  "Team Square est a 25 minutes de Lille par l'A1, 10 minutes de Lens et de Douai, 20 minutes d'Arras, avec un **parking gratuit et surveille**. Un point de rendez-vous central pour reunir un groupe venu de plusieurs villes, avec tout sur place : activites, bar et restauration."),
],
"venue": [
 (("acces","accès","parking"),
  "Vos invites viennent de toute la region pour {un} {loc} ? L'acces et le stationnement sont un vrai atout ici.",
  "Un acces facile, un parking gratuit",
  "Team Square est a Henin-Beaumont, a 25 minutes de Lille par l'A1, 10 minutes de Lens et de Douai, 20 minutes d'Arras, avec un **parking gratuit et surveille**. Un point de rendez-vous central pour reunir des invites venus de plusieurs villes, sans souci de stationnement."),
 (("sono","dj","musique"),
  "Quid de la musique et de la sonorisation pour {un} {loc} ? On fait le point sur ce qui est inclus et les options.",
  "Sonorisation et DJ",
  "Chaque salle est equipee d'une **enceinte amplifiee** incluse pour une sonorisation simple. Pour aller plus loin, on propose un DJ professionnel ou un pack sono autonome (a chiffrer), et vous pouvez aussi venir avec votre propre DJ. On cale tout ca au devis puis au rendez-vous des 15 jours."),
 (("visiter","visite"),
  "Peut-on visiter les salles avant de reserver {un} {loc} ? Voir le lieu aide a se projeter, on vous explique.",
  "Visiter avant de s'engager",
  "Rien de tel que de voir l'espace pour imaginer votre evenement. Contactez l'equipe pour convenir d'un creneau de visite et echanger sur votre projet (date, invites, envies). On en profite pour batir un devis detaille, valable 30 jours, et vous repartez avec une vision claire."),
 (("serveur","service a table","service à table","vaisselle"),
  "Service a table, vaisselle, serveurs : comment ca se passe pour {un} {loc} ? On detaille ce qui est prevu.",
  "Service et vaisselle",
  "Dans la formule cle en main, le **traiteur est servi par nos equipes** et la **vaisselle et la verrerie sont incluses**. Une option **serveur dedie** (recommandee a partir d'environ 80 personnes ou pour un service continu) est disponible. Les boissons sont en libre-service ou au ticket selon la formule."),
 (("animaux","animal","chien"),
  "Les animaux sont-ils acceptes pour {un} {loc} ? La regle est simple, on vous l'explique.",
  "Animaux : ce qui est permis",
  "Les animaux sont **toleres dans la salle privatisee** (espace prive que vous louez), meme s'ils restent interdits dans les espaces publics du complexe. Les **chiens d'assistance** sont quant a eux toujours admis. Pour tout cas particulier, signalez-le a la reservation."),
 (("photographe","photobooth"),
  "Comment garder une belle trace de {un} {loc} ? Photographe, photobooth : on vous presente les options.",
  "Photographe et photobooth",
  "Au-dela de la salle et du traiteur, on peut prevoir des animations en option pour immortaliser l'evenement : photographe, stand photo ou photobooth. Les photos et videos sont les bienvenues. On en discute au devis puis au rendez-vous des 15 jours pour caler le jour J."),
 (("plan de table","disposition"),
  "Comment agencer la salle et placer vos invites pour {un} {loc} ? On vous aide a penser le plan de table.",
  "Plan de table et disposition de la salle",
  "Tables rondes (jusqu'a 10 personnes) ou rectangulaires, mange-debout, espace cocktail ou repas assis : la salle se module selon votre format. On cale la disposition et le plan de table au **rendez-vous des 15 jours**, avec le mobilier inclus (tables, chaises, videoprojecteur, sonorisation)."),
 (("combien de temps","dure la location"),
  "Combien de temps dure la location pour {un} {loc} ? On clarifie les horaires et la mise a disposition.",
  "Duree de location et horaires",
  "La salle privatisee est a vous pour l'evenement, avec une mise a disposition possible la veille pour la decoration (selon disponibilite). Grace a un membre d'astreinte, la fete peut se prolonger **jusqu'a 5 h du matin**, n'importe quel jour de la semaine. On precise les creneaux au devis selon votre formule."),
],
"b2b": [
 (("rentree","rentrée","seminaire de rentree","séminaire de rentrée"),
  "Vous preparez {un} {loc} pour relancer la dynamique a la rentree ? Voici comment marquer le coup cote equipes.",
  "Un seminaire de rentree qui federe",
  "Salle de reunion equipee le matin, activites de cohesion l'apres-midi, dejeuner sur place : tout au meme endroit a 25 minutes de Lille, sans deplacement. La formule seminaire tout inclus (des 5 personnes) simplifie l'organisation. Anticipez : septembre et la fin d'annee partent vite. Devis detaille valable 30 jours."),
 (("formation","former","apprentissage"),
  "Vous organisez {un} {loc} avec un volet formation ? On combine apprentissage et mise en pratique sur une meme journee.",
  "Formation et mise en pratique",
  "La **formule formation professionnelle** (a partir de 5 personnes) reunit petit-dejeuner, salle de reunion, dejeuner, et activites de mise en pratique : cohesion, performance, gestion du stress ou des conflits, communication interne. Un cadre tout compris et un interlocuteur unique pour une journee efficace."),
 (("incentive","recompenser","récompenser","motiver"),
  "Envie de recompenser et motiver vos equipes avec {un} {loc} ? Une journee incentive bien pensee marque durablement.",
  "Recompenser et motiver les equipes",
  "On compose une journee a sensations et conviviale : plusieurs activites au choix parmi plus de 22, un dejeuner ou un cocktail sur place, et un cadre qui change du bureau. Ideal pour remercier une equipe apres un effort. On adapte le programme a vos effectifs et a votre budget, sur devis."),
 (("acces","accès","transport"),
  "Vos collaborateurs viennent de plusieurs sites pour {un} {loc} ? L'acces facile fait gagner du temps a tout le monde.",
  "Un site facile d'acces",
  "Team Square est a 25 minutes de Lille par l'A1, 10 minutes de Lens et de Douai, 20 minutes d'Arras, avec un **parking gratuit et surveille**. Un point de rendez-vous central pour reunir des equipes venues de toute la region, sans casse-tete logistique."),
 (("cse","comite","comité","arbre de noel","arbre de noël"),
  "Vous organisez un evenement {loc} pour votre CE ou CSE ? Du sur-mesure pour reunir collaborateurs et familles.",
  "Une journee CSE cle en main",
  "Formule **tout inclus sur site** (activites illimitees, stand photo, candy bar) ou **billetterie CSE** a tarif preferentiel : on adapte a votre comite. Espace privatisable, restauration sur place, et plus de 22 activites pour petits et grands. Parfait aussi pour un arbre de Noel. On batit la formule selon votre effectif."),
 (("sur mesure","sur-mesure","personnalise","personnalisé"),
  "Votre {a} {loc} sort des cases habituelles ? On construit une journee sur mesure autour de vos objectifs.",
  "Une journee sur mesure",
  "Effectifs, objectifs, contraintes, budget : on part de vos besoins pour assembler salles, activites et restauration en un programme coherent. Un interlocuteur unique coordonne tout, du devis au jour J. On adapte le format pour qu'il vous ressemble."),
 (("fin d'annee","fin d'année","novembre","decembre","décembre"),
  "Vous visez une date en fin d'annee pour {un} {loc} ? C'est la periode la plus demandee, voici comment securiser votre creneau.",
  "Securiser sa date en fin d'annee",
  "Novembre et decembre concentrent arbres de Noel et seminaires : les creneaux partent tres vite. Plus vous reservez tot, plus vous avez de choix de salle et de dates. Decrivez votre projet et on bloque votre creneau des l'acompte. Devis detaille valable 30 jours."),
 (("grand groupe","grands groupes","centaines"),
  "Vous reunissez un grand groupe pour {un} {loc} ? Le site est taille pour les effectifs importants.",
  "Accueillir un grand groupe",
  "Avec 7 500 m2 indoor, de vastes espaces outdoor et plusieurs salles, on accueille de grands effectifs, jusqu'a plusieurs centaines de personnes en rotation sur les activites. On dimensionne l'encadrement et le planning a votre nombre. Restauration sur place et un interlocuteur unique."),
]}

TOPICS_EXTRA = {
"loisir": [
 "{ACT} {loc} entre amis : la sortie qui met tout le monde d'accord",
 "{ACT} {loc} pour un groupe d'ados : l'activite qui plait",
 "{ACT} {loc} : sensations fortes garanties",
 "{ACT} {loc} : pourquoi ca vaut le coup d'essayer",
 "{ACT} {loc} en derniere minute : on vous accueille rapidement",
 "{ACT} {loc} : -10 % en ligne avec le code promo TS10",
 "{ACT} {loc} : une sortie ouverte a tous",
 "{ACT} {loc} : la version nocturne a decouvrir",
 "{ACT} {loc} : quelle activite choisir selon votre groupe",
 "{ACT} {loc} : et si vous enchainiez plusieurs activites ?",
],
"party": [
 "{ACT} {loc} : garder un souvenir memorable de l'evenement",
 "{ACT} {loc} en petit comite : reussir la fete a quelques-uns",
 "{ACT} {loc} : donner un theme et creer l'ambiance",
 "{ACT} {loc} : peut-on apporter son gateau ?",
 "{ACT} {loc} : boissons avec ou sans alcool",
 "{ACT} {loc} : la tournee de boissons offerte",
 "{ACT} {loc} : le karaoke pour finir en chansons",
 "{ACT} {loc} : acces et parking pour le groupe",
],
"venue": [
 "{ACT} {loc} : acces facile et parking gratuit",
 "{ACT} {loc} : sonorisation, DJ et musique",
 "{ACT} {loc} : peut-on visiter la salle avant de s'engager ?",
 "{ACT} {loc} : service a table, serveurs et vaisselle",
 "{ACT} {loc} : les animaux sont-ils acceptes ?",
 "{ACT} {loc} : photographe et photobooth en option",
 "{ACT} {loc} : plan de table et disposition de la salle",
 "{ACT} {loc} : combien de temps dure la location ?",
],
"b2b": [
 "{ACT} {loc} : reussir un seminaire de rentree",
 "{ACT} {loc} : allier formation et mise en pratique",
 "{ACT} {loc} : une journee incentive pour recompenser les equipes",
 "{ACT} {loc} : un site facile d'acces pour vos collaborateurs",
 "{ACT} {loc} : une journee CSE ou un arbre de Noel",
 "{ACT} {loc} : une journee d'entreprise sur mesure",
 "{ACT} {loc} : securiser sa date en fin d'annee",
 "{ACT} {loc} : accueillir un grand groupe d'entreprise",
]}
